Integrator class
MolSSI-Education/mm_2019_sss_3 pull request #10
Opened 2019-07-26 21:25 UTC by sabiharustam

I have clean up the Integrator class object.
Functions included:

- [ ]  __init__ : Please check if I have included redundant inputs. 

- [ ]   get_particle_energy: I cannot wrap my head around this function. please check to make sure this actually works.

- [ ] accept_or_reject: delta_e is calculated, but requires beta from outside of this class as input.

- [ ] adjust_displacement: acc_rate is input. MC class should give this. check if this is true.

- [ ]   __call__ : Does this serve the purpose?

2019-07-26 22:01 UTC, b-butler requested changes

2019-07-26 22:01 UTC, b-butler commented on integrator_class.py
> +                 cutoff=3.0,
Don't need `cutoff`.

2019-07-26 22:01 UTC, b-butler commented on integrator_class.py
> +            max_displacement *= 0.8
Maybe use 0.9 and 1.1. These changes are a little large.

2019-07-26 22:05 UTC, ZL-Song approved these changes

2019-07-27 02:03 UTC, b-butler approved these changes

2019-07-27 02:03 UTC, merged